// moltarc v0.1 — tiered SQLite archive: hot WAL -> warm chunks -> cold relay + manifest.
export { seal, readHotRows, readSqliteRows, isSqliteFile, normRow, chunkName, TARGET_BYTES, MIN_BYTES, MAX_BYTES } from './seal.js';
export type { SealOpts, SealResult } from './seal.js';
export { buildManifest, saveManifestAtomic, loadManifest, rebuildFromFilenames, buildBloom, bloomCheck, acquireManifestLock, withManifestLock, readManifestLockPid } from './manifest.js';
export type { ChunkEntry, ColdSegment, Manifest } from './manifest.js';
export { ship, planShipment, sendChunked, readRelayIndex, laneOf } from './ship.js';
export type { ShipOpts, ShipResult, RelayIndex } from './ship.js';
export { findTrx, candidates, buildSparseIndex } from './find.js';
export type { FindOpts, FindResult, SparseEntry } from './find.js';
export { verifyChunk, verifyAll, verifyFull, repairAll, quarantine, repairByHash } from './verify.js';
export type { VerifyItem, VerifyResult, VerifyFullResult, FullVerifyItem, ChunkStatus, ManifestCheck, ChainBreak, RepairResult, RepairFailure } from './verify.js';
export { encodeChunk, decodeChunk, encodeHeader, decodeHeader, crc32c, sha256hex, fnv1a32, DICT_FLAG } from './chunk.js';
export { trainTableDict, saveDictAtomic, loadDictFor, dictFile, dictHex, DICT_MAX_BYTES, DICT_TRAIN_ROWS } from './dict.js';
export { sweep, statusInfo, checkReserve, freeSpaceBytes, RESERVE_BYTES } from './gc.js';
export type { SweepOpts, SweepResult, StatusInfo } from './gc.js';
export { mergeCold, forgetChunks, sweepCold, coldDiskBytes, writeTar, readTar } from './cold.js';
export type { MergeResult, ColdSweepOpts, ColdSweepResult, RepackedSeg, TarMember } from './cold.js';
export * from './p2p.js';
export * from './timetravel.js';
export * from './migrate.js';
export * from './readonly.js';
export * from './alerts.js';
export * from './sensor.js';
export * from './claim.js';
export * from './bundle.js';
export * from './thumb.js';
export * from './cas.js';
